name: Manage Google Cloud Pub Sub Topics and Subscriptiongs
author: Deskbird
description: |-
  Use this action to ensure the required pubsub subscirptions are in place.

inputs:
  project_id:
    description: |-
      The Google Cloud Project ID. If unset, this is inherited from the environment.
    required: false

  client_name:
    description: |-
      The name of the client. This is used to create the subscription name.
    required: true

  push_auth_service_account:
    description: |-
      The service account to use for push authentication.
    required: true

  push_auth_token_audience:
    description: |-
      The audience to use for push authentication.
    required: true

  ack_deadline:
    description: |-
      The amount of time Pub/Sub waits for the subscriber to acknowledge receipt
      before resending the message. If unset, the default value of 10 seconds is
      used.
    required: false
    default: 20

  min_retry_delay:
    description: |-
      The minimum amount of time to wait before retrying a task after it fails.
    required: false
    default: 5
  
  max_retry_delay:
    description: |-
      The maximum amount of time to wait before retrying a task after it fails.
    required: false
    default: 60

  max_delivery_attempts:
    description: |-
      The maximum number of times to retry delivery of a task after a task fails.
    required: false
    default: 5
  
  topics:
    description: |-
      List of topics to create.
    required: false

  subscriptiongs:
    description: |-
      List of subscriptions to create:
      topic=endpoint
    required: false

  region:
    description: |-
      Region in which the resource can be found.
    required: false
    default: us-central1

  labels:
    description: |-
      List of key-value pairs to set as labels of cloud run service in the format:
      KEY1=VALUE1,KEY2=VALUE2. Existing labels will be retained.
    required: false

# outputs:
#   url:
#     description: The URL of your Cloud Run service

branding:
  icon: 'chevrons-right'
  color: 'blue'

runs:
  using: 'node16'
  main: 'dist/main/index.js'
